wandb_version: 1

train_dataset_path:
  desc: null
  value: C:\Users\jolged\PycharmProjects\Auto_Recognition2\data\v1.1.0\train
test_dataset_path:
  desc: null
  value: C:\Users\jolged\PycharmProjects\Auto_Recognition2\data\v1.1.0\test
labels:
  desc: null
  value: inferred
label_mode:
  desc: null
  value: binary
color_mode:
  desc: null
  value: rgb
batch_size:
  desc: null
  value: 35
image_size:
  desc: null
  value:
  - 224
  - 224
shuffle:
  desc: null
  value: false
seed:
  desc: null
  value: 42
modelis:
  desc: null
  value: "\n                model = keras.Sequential([\n                #     layers.experimental.preprocessing.Rescaling(1./255,\
    \ input_shape=tuple(config.image_size) + (3,)),\n                    layers.Conv2D(128,\
    \ (3, 3), activation='relu', input_shape=tuple(config.image_size) + (3,)),\n \
    \                   layers.Conv2D(128, (3, 3), activation='relu'),\n         \
    \           layers.MaxPooling2D((2,2)),\n                    layers.Dropout(0.2),\n\
    \                    layers.Conv2D(64, (3, 3), activation=\"relu\"),\n       \
    \             layers.MaxPooling2D((2,2)),\n                    layers.Dropout(0.2),\n\
    \                    layers.Conv2D(32, (3, 3), activation=\"relu\"),\n       \
    \             layers.MaxPooling2D((2,2)),\n                    layers.Flatten(),\n\
    \                    layers.Dense(128, activation=\"relu\"),\n               \
    \     layers.Dense(1, activation=\"sigmoid\"),\n                ])\n        "
model_name:
  desc: null
  value: model_v1.1.0_1684350745.hdf5
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: binary_crossentropy
metrics:
  desc: null
  value:
  - accuracy
  - Precision
  - Recall
  - AUC
  - FalseNegatives
  - FalsePositives
  - TrueNegatives
  - TruePositives
epoch:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.14.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684350750.089263
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.10.7
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
    viz:
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
